FROM quay.io/biocontainers/fastqc:0.11.9--0

LABEL "MAINTAINER"="icaoberg"
LABEL "EMAIL"="icaoberg@psc.edu"
LABEL "SUPPORT"="help@psc.edu"
LABEL "REPOSITORY"="http://github.com/pscedu/singularity-fastqc"
LABEL "COPYRIGHT"="Copyright © 2023-2023 Pittsburgh Supercomputing Center. All Rights Reserved."
LABEL "VERSION"="0.11.9"

ENV LC_ALL C.UTF-8
RUN locale
