Bootstrap: docker
From: quay.io/biocontainers/fastqc:0.11.9--0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 0.11.9

%post
   rm /etc/resolv.conf

####################################################################################
